from enum import Enum

class RequesterRole(str, Enum):
    EMPLOYER = 'EMPLOYER'
    LANDLORD = 'LANDLORD'
    EDUCATION = 'EDUCATION'
    BORDER_CONTROL = 'BORDER_CONTROL'
    LAW_ENFORCEMENT = 'LAW_ENFORCEMENT'

class Purpose(str, Enum):
    EMPLOYMENT = 'EMPLOYMENT'
    ACCOMMODATION = 'ACCOMMODATION'
    EDUCATION = 'EDUCATION'
    BORDER_ENTRY = 'BORDER_ENTRY'
    LAW_ENFORCEMENT = 'LAW_ENFORCEMENT'

class VerificationRoute(str, Enum):
    SHARE_CODE = 'SHARE_CODE'
    DOCUMENT = 'DOCUMENT'

class OutcomeStatus(str, Enum):
    ELIGIBLE = 'ELIGIBLE'
    NOT_ELIGIBLE = 'NOT_ELIGIBLE'
    EXPIRED = 'EXPIRED'
    INVALID_INPUT = 'INVALID_INPUT'
    UNAUTHORISED = 'UNAUTHORISED'
    PURPOSE_MISMATCH = 'PURPOSE_MISMATCH'
    NOT_FOUND = 'NOT_FOUND'
    IDENTITY_MISMATCH = 'IDENTITY_MISMATCH'
    CONFIRMATIONS_MISSING = 'CONFIRMATIONS_MISSING'
ROLE_PURPOSE_MAP = {RequesterRole.EMPLOYER: {Purpose.EMPLOYMENT}, RequesterRole.LANDLORD: {Purpose.ACCOMMODATION}, RequesterRole.EDUCATION: {Purpose.EDUCATION}, RequesterRole.BORDER_CONTROL: {Purpose.BORDER_ENTRY}, RequesterRole.LAW_ENFORCEMENT: {Purpose.LAW_ENFORCEMENT}}
AUTHORITY_ROLES = {RequesterRole.BORDER_CONTROL, RequesterRole.LAW_ENFORCEMENT}
SHARE_CODE_ROLES = {RequesterRole.EMPLOYER, RequesterRole.LANDLORD, RequesterRole.EDUCATION}
